import { NbMenuItem } from '@nebular/theme';

export enum Roles {
  /**
     Home page after login
    */
  ADMIN_HOME = 'XPA_ADMIN_HOME',

  ADMIN_READ = 'XPA_ADMIN_READ',
  ADMIN_CREATE = 'XPA_ADMIN_CREATE',
  ADMIN_UPDATE = 'XPA_ADMIN_UPDATE',
  ADMIN_DETAIL = 'XPA_ADMIN_DETAIL',

  ADMIN_RESET_PASSWORD_AUTO = 'XPA_ADMIN_RESET_PASSWORD_AUTO',
  ADMIN_RESET_PASSWORD_MANUAL = 'XPA_ADMIN_RESET_PASSWORD_MANUAL',
  ADMIN_RESET_PASSWORD = 'XPA_ADMIN_PASSWORD_RESET',

  ADMIN_UNBLOCK = 'XPA_ADMIN_UNBLOCK',
  ADMIN_UNBLOCK_APPROVE = 'XPA_ADMIN_UNBLOCK_APPROVE',
  ADMIN_BLOCK = 'XPA_ADMIN_BLOCK',
  ADMIN_DELETE = 'XPA_ADMIN_DELETE',

  APP_SETUP = 'XPA_APP_SETUP',

  //admin profile
  ADMIN_PROFILE_CREATE = 'XPA_ADMIN_PROFILE_CREATE',
  ADMIN_PROFILE_READ = 'XPA_ADMIN_PROFILE_READ',
  ADMIN_PROFILE_UPDATE = 'XPA_ADMIN_PROFILE_UPDATE',
  ADMIN_PROFILE_DETAIL = 'XPA_ADMIN_PROFILE_DETAIL',
  ADMIN_PROFILE_UNBLOCK = 'XPA_ADMIN_PROFILE_UNBLOCK',
  ADMIN_PROFILE_BLOCK = 'XPA_ADMIN_PROFILE_BLOCK',
  ADMIN_PROFILE_DELETE = 'XPA_ADMIN_PROFILE_DELETE',

  //customer profile
  CUSTOMER_PROFILE_READ = 'XPA_CUSTOMER_PROFILE_READ ',
  CUSTOMER_PROFILE_CREATE = 'XPA_CUSTOMER_PROFILE_CREATE',
  CUSTOMER_PROFILE_UPDATE = 'XPA_CUSTOMER_PROFILE_UPDATE',
  CUSTOMER_PROFILE_DETAIL = 'XPA_CUSTOMER_PROFILE_DETAIL',
  CUSTOMER_PROFILE_BLOCK = 'XPA_CUSTOMER_PROFILE_BLOCK',

  //ADMIN MENU
  MENU_HOME = 'XPA_MENU_HOME',
  MENU_READ = 'XPA_MENU_READ',
  MENU_CREATE = 'XPA_MENU_CREATE',
  MENU_UPDATE = 'XPA_MENU_UPDATE',
  MENU_DETAIL = 'XPA_MENU_DETAIL',

  //CUSTOMER MENU
  CUSTOMER_MENU_READ = 'XPA_CUSTOMER_MENU_READ',
  CUSTOMER_MENU_CREATE = 'XPA_CUSTOMER_MENU_CREATE',
  CUSTOMER_MENU_UPDATE = 'XPA_CUSTOMER_MENU_UPDATE',
  CUSTOMER_MENU_DETAIL = 'XPA_CUSTOMER_MENU_DETAIL',

  //customer
  CUSTOMER = 'XPA_CUSTOMER',
  CUSTOMER_READ = 'XPA_CUSTOMER_READ',
  CUSTOMER_CREATE = 'XPA_CUSTOMER_CREATE',
  CUSTOMER_UPDATE = 'XPA_CUSTOMER_UPDATE',
  CUSTOMER_DETAIL = 'XPA_CUSTOMER_DETAIL',
  CUSTOMER_UNBLOCK_INITIATE = 'XPA_CUSTOMER_UNBLOCK_INITIATE',
  CUSTOMER_UNBLOCK_APPROVE = 'XPA_CUSTOMER_UNBLOCK_APPROVE',
  CUSTOMER_RESET_SERVICE = 'XPA_CUSTOMER_RESET_SERVICE',
  CUSTOMER_BLOCK = 'XPA_CUSTOMER_BLOCK',
  CUSTOMER_UNBLOCK = 'XPA_CUSTOMER_UNBLOCK',
  CUSTOMER_REGISTER_CREDIT_CARD = 'XPA_CUSTOMER_REGISTER_CREDIT_CARD',
  CUSTOMER_ACTIVITY = 'XPA_CUSTOMER_ACTIVITY',
  CUSTOMER_MODIFY_REVERT = 'XPA_CUSTOMER_MODIFY_REVERT',
  CUSTOMER_APPROVE = 'XPA_CUSTOMER_APPROVE',
  CUSTOMER_REJECT = 'XPA_CUSTOMER_REJECT',
  CUSTOMER_DELETE = 'XPA_CUSTOMER_DELETE',
  CUSTOMER_PASSWORD_RESET = 'XPA_CUSTOMER_PASSWORD_RESET',
  CUSTOMER_MODIFY_APPROVE = 'XPA_CUSTOMER_MODIFY_APPROVE',
  CUSTOMER_MODIFY_REJECT = 'XPA_CUSTOMER_MODIFY_REJECT',
  CUSTOMER_ADVANCED_SEARCH = 'XPA_CUSTOMER_ADVANCED_SEARCH',

  //branch
  BRANCH_READ = 'XPA_BRANCH_READ',
  BRANCH_CREATE = 'XPA_BRANCH_CREATE',
  BRANCH_UPDATE = 'XPA_BRANCH_UPDATE',
  BRANCH_DETAIL = 'XPA_BRANCH_DETAIL',

  //atmLocation

  ATM_LOCATION_READ = 'XPA_ATM_LOCATION_READ',
  ATM_LOCATION_CREATE = 'XPA_ATM_LOCATION_CREATE',
  ATM_LOCATION_UPDATE = 'XPA_ATM_LOCATION_UPDATE',
  ATM_LOCATION_DETAIL = 'XPA_ATM_LOCATION_DETAIL',


  PROVINCE_READ = 'XPA_PROVINCE_READ',


  ACCOUNT_TYPE_READ = 'XPA_ACCOUNT_TYPE_READ',
  ACCOUNT_TYPE_CREATE = 'XPA_ACCOUNT_TYPE_CREATE',
  ACCOUNT_TYPE_UPDATE = 'XPA_ACCOUNT_TYPE_UPDATE',
  ACCOUNT_TYPE_DETAIL = 'XPA_ACCOUNT_TYPE_DETAIL',


  RESET_DEVICE = 'XPA_RESET_DEVICE',
  CUSTOMER_RESET_PASSWORD = 'XPA_CUSTOMER_PASSWORD_RESET',
  SEND_EMAIL_VERIFICATION = 'XPA_SEND_EMAIL_VERIFICATION',
  //settings

  //resend sms
  RESEND_SMS = 'XPA_RESEND_SMS',

  SETTINGS = 'XPA_SETTINGS',

  //system config master
  SYSTEM_CONFIG_MASTER_READ = 'XPA_SYSTEM_CONFIG_MASTER_READ',
  SYSTEM_CONFIG_MASTER_CREATE = 'XPA_SYSTEM_CONFIG_MASTER_CREATE',
  SYSTEM_CONFIG_MASTER_UPDATE = 'XPA_SYSTEM_CONFIG_MASTER_UPDATE',
  SYSTEM_CONFIG_MASTER_DETAIL = 'XPA_SYSTEM_CONFIG_MASTER_DETAIL',

  //system config
  SYSTEM_CONFIG_READ = 'XPA_SYSTEM_CONFIG_READ',
  SYSTEM_CONFIG_CREATE = 'XPA_SYSTEM_CONFIG_CREATE',
  SYSTEM_CONFIG_UPDATE = 'XPA_SYSTEM_CONFIG_UPDATE',
  SYSTEM_CONFIG_DETAIL = 'XPA_SYSTEM_CONFIG_DETAIL',

  //admin message format
  ADMIN_MESSAGE_FORMAT_READ = 'XPA_ADMIN_MESSAGE_FORMAT_READ',
  ADMIN_MESSAGE_FORMAT_CREATE = 'XPA_ADMIN_MESSAGE_FORMAT_CREATE',
  ADMIN_MESSAGE_FORMAT_UPDATE = 'XPA_ADMIN_MESSAGE_FORMAT_UPDATE',
  ADMIN_MESSAGE_FORMAT_DETAIL = 'XPA_ADMIN_MESSAGE_FORMAT_DETAIL',

  //message format
  MESSAGE_FORMAT_READ = 'XPA_MESSAGE_FORMAT_READ',
  MESSAGE_FORMAT_CREATE = 'XPA_MESSAGE_FORMAT_CREATE',
  MESSAGE_FORMAT_UPDATE = 'XPA_MESSAGE_FORMAT_UPDATE',
  MESSAGE_FORMAT_DETAIL = 'XPA_MESSAGE_FORMAT_DETAIL',

  //content setup
  CONTENT_SETUP_READ = 'XPA_CONTENT_SETUP_READ',
  CONTENT_SETUP_CREATE = 'XPA_CONTENT_SETUP_CREATE',
  CONTENT_SETUP_UPDATE = 'XPA_CONTENT_SETUP_UPDATE',
  CONTENT_SETUP_DETAIL = 'XPA_CONTENT_SETUP_DETAIL',

  //feature setup
  FEATURE_SETUP = 'XPA_FEATURE_SETUP',

  //feature
  FEATURE_READ = 'XPA_FEATURE_READ',
  FEATURE_CREATE = 'XPA_FEATURE_CREATE',
  FEATURE_UPDATE = 'XPA_FEATURE_UPDATE',
  FEATURE_DETAIL = 'XPA_FEATURE_DETAIL',

  //application pattern
  APPLICATION_PATTERN_READ = 'XPA_APPLICATION_PATTERN_READ',
  APPLICATION_PATTERN_CREATE = 'XPA_APPLICATION_PATTERN_CREATE',
  APPLICATION_PATTERN_UPDATE = 'XPA_APPLICATION_PATTERN_UPDATE',
  APPLICATION_PATTERN_DETAIL = 'XPA_APPLICATION_PATTERN_DETAIL',

  //merchant setup
  MERCHANT_SETUP = 'XPA_MERCHANT_SETUP',

  //messaging
  MESSAGING = 'XPA_MESSAGING',

  MERCHANT_GROUP_READ = 'XPA_MERCHANT_GROUP_READ',
  MERCHANT_GROUP_CREATE = 'XPA_MERCHANT_GROUP_CREATE',
  MERCHANT_GROUP_UPDATE = 'XPA_MERCHANT_GROUP_UPDATE',
  MERCHANT_GROUP_DETAIL = 'XPA_MERCHANT_GROUP_DETAIL',

  MERCHANT_GROUP_ICON_READ = 'XPA_MERCHANT_GROUP_ICON_READ',
  MERCHANT_GROUP_ICON_CREATE = 'XPA_MERCHANT_GROUP_ICON_CREATE',
  MERCHANT_GROUP_ICON_UPDATE = 'XPA_MERCHANT_GROUP_ICON_UPDATE',
  MERCHANT_GROUP_ICON_DETAIL = 'XPA_MERCHANT_GROUP_ICON_DETAIL',

  MERCHANT_TYPE_READ = 'XPA_MERCHANT_TYPE_READ',
  MERCHANT_TYPE_CREATE = 'XPA_MERCHANT_TYPE_CREATE',
  MERCHANT_TYPE_UPDATE = 'XPA_MERCHANT_TYPE_UPDATE',
  MERCHANT_TYPE_DETAIL = 'XPA_MERCHANT_TYPE_DETAIL',

  MERCHANT_READ = 'XPA_MERCHANT_READ',
  MERCHANT_CREATE = 'XPA_MERCHANT_CREATE',
  MERCHANT_UPDATE = 'XPA_MERCHANT_UPDATE',
  MERCHANT_DETAIL = 'XPA_MERCHANT_DETAIL',

  PAYMENT_TYPE_READ = 'XPA_PAYMENT_TYPE_READ',
  PAYMENT_TYPE_CREATE = 'XPA_PAYMENT_TYPE_CREATE',
  PAYMENT_TYPE_UPDATE = 'XPA_PAYMENT_TYPE_UPDATE',
  PAYMENT_TYPE_DETAIL = 'XPA_PAYMENT_TYPE_DETAIL',

  //sms keyword
  SMS_KEYWORD_READ = 'XPA_SMS_KEYWORD_READ',
  SMS_KEYWORD_CREATE = 'XPA_SMS_KEYWORD_CREATE',
  SMS_KEYWORD_UPDATE = 'XPA_SMS_KEYWORD_UPDATE',
  SMS_KEYWORD_DETAIL = 'XPA_SMS_KEYWORD_DETAIL',

  //key access mode
  KEY_ACCESS_MODE_READ = 'XPA_KEY_ACCESS_MODE_READ',
  KEY_ACCESS_MODE_CREATE = 'XPA_KEY_ACCESS_MODE_CREATE',
  KEY_ACCESS_MODE_UPDATE = 'XPA_KEY_ACCESS_MODE_UPDATE',
  KEY_ACCESS_MODE_DETAIL = 'XPA_KEY_ACCESS_MODE_DETAIL',

  //merchant parameter input
  MERCHANT_PARAMETER_INPUT_READ = 'XPA_MERCHANT_PARAMETER_INPUT_READ',
  MERCHANT_PARAMETER_INPUT_CREATE = 'XPA_MERCHANT_PARAMETER_INPUT_CREATE',
  MERCHANT_PARAMETER_INPUT_UPDATE = 'XPA_MERCHANT_PARAMETER_INPUT_UPDATE',
  MERCHANT_PARAMETER_INPUT_DETAIL = 'XPA_MERCHANT_PARAMETER_INPUT_DETAIL',

  COMMISSION_SLAB_READ = 'XPA_COMMISSION_SLAB_READ',
  COMMISSION_SLAB_CREATE = 'XPA_COMMISSION_SLAB_CREATE',
  COMMISSION_SLAB_UPDATE = 'XPA_COMMISSION_SLAB_UPDATE',
  COMMISSION_SLAB_DETAIL = 'XPA_COMMISSION_SLAB_DETAIL',

  //payment code pattern
  PAYMENT_CODE_PATTERN_READ = 'XPA_PAYMENT_CODE_PATTERN_READ',
  PAYMENT_CODE_PATTERN_CREATE = 'XPA_PAYMENT_CODE_PATTERN_CREATE',
  PAYMENT_CODE_PATTERN_UPDATE = 'XPA_PAYMENT_CODE_PATTERN_UPDATE',
  PAYMENT_CODE_PATTERN_DETAIL = 'XPA_PAYMENT_CODE_PATTERN_DETAIL',

  //payment code type
  PAYMENT_CODE_TYPE_READ = 'XPA_PAYMENT_CODE_TYPE_READ',
  PAYMENT_CODE_TYPE_CREATE = 'XPA_PAYMENT_CODE_TYPE_CREATE',
  PAYMENT_CODE_TYPE_UPDATE = 'XPA_PAYMENT_CODE_TYPE_UPDATE',
  PAYMENT_CODE_TYPE_DETAIL = 'XPA_PAYMENT_CODE_TYPE_DETAIL',

  // commission mode
  COMMISSION_MODE_READ = 'XPA_COMMISSION_MODE_READ',
  COMMISSION_MODE_CREATE = 'XPA_COMMISSION_MODE_CREATE',
  COMMISSION_MODE_UPDATE = 'XPA_COMMISSION_MODE_UPDATE',
  COMMISSION_MODE_DETAIL = 'XPA_COMMISSION_MODE_DETAIL',

  //commission type
  COMMISSION_TYPE_READ = 'XPA_COMMISSION_TYPE_READ',
  COMMISSION_TYPE_CREATE = 'XPA_COMMISSION_TYPE_CREATE',
  COMMISSION_TYPE_UPDATE = 'XPA_COMMISSION_TYPE_UPDATE',
  COMMISSION_TYPE_DETAIL = 'XPA_COMMISSION_TYPE_DETAIL',

  //offer category
  PRODUCT_CATEGORY_READ = 'XPA_PRODUCT_CATEGORY_READ',
  PRODUCT_CATEGORY_CREATE = 'XPA_PRODUCT_CATEGORY_CREATE',
  PRODUCT_CATEGORY_UPDATE = 'XPA_PRODUCT_CATEGORY_UPDATE',
  PRODUCT_CATEGORY_DETAIL = 'XPA_PRODUCT_CATEGORY_DETAIL',

  //merchant icon
  MERCHANT_ICON_READ = 'XPA_MERCHANT_ICON_READ',
  MERCHANT_ICON_CREATE = 'XPA_MERCHANT_ICON_CREATE',
  MERCHANT_ICON_UPDATE = 'XPA_MERCHANT_ICON_UPDATE',
  MERCHANT_ICON_DETAIL = 'XPA_MERCHANT_ICON_DETAIL',

  //merchant service
  MERCHANT_SERVICE_READ = 'XPA_MERCHANT_SERVICE_READ',
  MERCHANT_SERVICE_CREATE = 'XPA_MERCHANT_SERVICE_CREATE',
  MERCHANT_SERVICE_UPDATE = 'XPA_MERCHANT_SERVICE_UPDATE',
  MERCHANT_SERVICE_DETAIL = 'XPA_MERCHANT_SERVICE_DETAIL',

  ADMIN_TELLER_READ = 'XPA_ADMIN_TELLER_READ',
  ADMIN_TELLER_DETAIL = 'XPA_ADMIN_TELLER_DETAIL',
  ADMIN_TELLER_DELETE = 'XPA_ADMIN_TELLER_DELETE',
  ADMIN_TELLER_CREATE = 'XPA_ADMIN_TELLER_CREATE',
  ADMIN_TELLER_BLOCK = 'XPA_ADMIN_TELLER_BLOCK',
  ADMIN_TELLER_UNBLOCK = 'XPA_ADMIN_TELLER_UNBLOCK',
  ADMIN_TELLER_UPDATE = 'XPA_ADMIN_TELLER_UPDATE',

  //Admin user activity
  ADMIN_USER_ACTIVITY = 'XPA_ADMIN_USER_ACTIVITY',

  CHARGE = 'XPA_CHARGE',
  BULK_CHARGE_UPLOAD = 'XPA_BULK_CHARGE_UPLOAD',
  BULK_CHARGE_APPROVE = 'XPA_BULK_CHARGE_APPROVE',

  //Commission partner
  COMMISSION_PARTNER_CREATE = 'XPA_COMMISSION_PARTNER_CREATE',
  COMMISSION_PARTNER_READ = 'XPA_COMMISSION_PARTNER_READ',
  COMMISSION_PARTNER_UPDATE = 'XPA_COMMISSION_PARTNER_UPDATE',
  COMMISSION_PARTNER_DETAIL = 'XPA_COMMISSION_PARTNER_DETAIL',
  //Product
  PRODUCT_SETUP = 'XPA_PRODUCT_SETUP',
  PRODUCT_CREATE = 'XPA_PRODUCT_CREATE',
  PRODUCT_READ = 'XPA_PRODUCT_READ',
  PRODUCT_DETAIL = 'XPA_PRODUCT_DETAIL',
  PRODUCT_DELETE = 'XPA_PRODUCT_DELETE',
  PRODUCT_UPDATE = 'XPA_PRODUCT_UPDATE',


  //fcm message
  FCM_MESSAGE_COMPOSE = 'XPA_FCM_MESSAGE_COMPOSE',

  //failed charge
  FAILED_CHARGE_READ = 'XPA_FAILED_CHARGE_READ',

  DEVICE_RESET_INITIATE = 'XPA_DEVICE_RESET_INITIATE',
  DEVICE_RESET_APPROVE = 'XPA_DEVICE_RESET_APPROVE',

  //renew charge
  RENEW_CHARGE_READ = 'XPA_RENEW_CHARGE_READ',
  FAILED_RENEW_CHARGE_READ = 'XPA_FAILED_RENEW_CHARGE_READ',
  APPROVE_RENEW_CHARGE_READ = 'XPA_APPROVE_RENEW_CHARGE_READ',

  //REQUEST
  REQUEST = 'XPA_REQUEST',

  SMS_BANKING = 'XPA_SMS_BANKING',

  //cbs query
  CBS_QUERY_CREATE = 'XPA_CBS_QUERY_CREATE',
  CBS_QUERY_UPDATE = 'XPA_CBS_QUERY_UPDATE',
  CBS_QUERY_READ = 'XPA_CBS_QUERY_READ',
  CBS_QUERY_DETAIL = 'XPA_CBS_QUERY_DETAIL',
  CBS_QUERY_EXECUTE = 'XPA_CBS_QUERY_EXECUTE',


  CBS_CONNECTION_CREATE = "CBS_CONNECTION_CREATE",
  CBS_CONNECTION_READ = "CBS_CONNECTION_READ",
  CBS_CONNECTION_UPDATE = "CBS_CONNECTION_UPDATE",
  CBS_CONNECTION_DETAIL = "CBS_CONNECTION_DETAIL",
  CBS_CONNECTION_TEST = "CBS_CONNECTION_TEST",


  //sms messaging
  SMS_MESSAGING = 'XPA_SMS_MESSAGING',
  //PROMOTION

  PROMOTION_CREATE = 'XPA_PROMOTION_CREATE',
  PROMOTION_UPDATE = 'XPA_PROMOTION_UPDATE',
  PROMOTION_DETAIL = 'XPA_PROMOTION_DETAIL',
  PROMOTION_READ = 'XPA_PROMOTION_READ',
  PROMOTION_DELETE = 'XPA_PROMOTION_DELETE',



  //fixedDeposit
  FIXED_DEPOSIT_APPROVE = 'XPA_FIXED_DEPOSIT_APPROVE',
  FIXED_DEPOSIT_REJECT = 'XPA_FIXED_DEPOSIT_REJECT',

  //gcm messaging
  FCM_MESSAGING = 'XPA_FCM_MESSAGING',

  CHARGE_SETUP = "CHARGE_SETUP",
  CHARGE_SETUP_CREATE = "CHARGE_SETUP_CREATE",
  CHARGE_SETUP_DETAIL = "CHARGE_SETUP_DETAIL",
  CHARGE_SETUP_UPDATE = "CHARGE_SETUP_UPDATE",

  //Email template
  EMAIL_TEMPLATE_READ = "EMAIL_TEMPLATE_READ",
  EMAIL_TEMPLATE_MODIFY = "EMAIL_TEMPLATE_MODIFY",


  //Fund Transfer 
  FUND_TRANSFER_READ = "FUND_TRANSFER_READ",

  COUNTER_PAYMENT = "COUNTER_PAYMENT",

  //Remittance 
  REMITTANCE_READ = "REMITTANCE_READ",
  REMITTANCE_MODIFY = "REMITTANCE_MODIFY",


  IBFT_FONEPAY_READ = "IBFT_FONEPAY_READ",
  IBFT_FONEPAY_RECONCILE = "IBFT_FONEPAY_RECONCILE",

  BLOCKED_API_READ = "BLOCKED_API_READ",
  BLOCKED_API_CREATE = 'XPA_BLOCKED_API_CREATE',
  BLOCKED_API_UPDATE = 'XPA_BLOCKED_API_UPDATE',
  BLOCKED_API_DETAIL = 'XPA_BLOCKED_API_DETAIL',


}